# pg-tileserv Docker Compose example setup.
#
# To build/run, see README.md
#
version: "3"

services:
  pg_rasterserv:
    image: pramsey/pg_rasterserv:latest-alpine-3.12
    build:
      context: ../..
      dockerfile: Dockerfile.alpine
      args:
        VERSION: latest-alpine-3.12

    container_name: pg_rasterserv

    env_file:
      - pg_rasterserv.env

    depends_on:
      - pg_rasterserv_db

    ports:
      - 7800:7800
    expose:
      - '7800'

  pg_rasterserv_db:
    image: postgis/postgis:16-3.5
    platform: linux/amd64

    container_name: pg_rasterserv_db

    volumes:
      - ./data:/work
      - ./db:/var/lib/postgresql/data

    environment:
      POSTGIS_ENABLE_OUTDB_RASTERS: "1"
      POSTGIS_GDAL_ENABLED_DRIVERS: "ENABLE_ALL"

    env_file:
      - pg.env

  static_file_server:
    image: nginx:alpine

    container_name: static_file_server

    volumes:
      - ../leaflet:/usr/share/nginx/html:ro

    ports:
      - 8080:80

  varnish:
    image: varnish:stable
    container_name: pg_rasterserv_cache
    depends_on:
      - pg_rasterserv
    ports:
      - "7801:80"
    volumes:
      - "./default.vcl:/etc/varnish/default.vcl"
    tmpfs:
      - /var/lib/varnish/varnishd:exec
    command: >
      -s malloc,256M -s file,/var/lib/varnish/diskcache,2G
    restart: unless-stopped
